### ISSUE TITLE
Does this work for changing Contribution graph?

### ISSUE THREAD

**Issue by jamesharrisivi** [rixx/git-backdate#12]
When I try git backdate origin/main "10 days ago..today" --business-hours it only has the commit as 2 days ago, and it doesn't appear on the contribution graph?

**Comment by rixx** [comment]
I assume you're talking about the grid graph on GitHub's profile pages.

I suspect GitHub caches commits it has seen before / does not update the graph in real time for repos it knows already. This tool does not serve to interface with GitHub directly, it changes your local git repository. `git log --pretty=fuller` can show you a commit with both its logged timestamps. If you force-push those commits to GitHub, it *should* pick them up, but like I said: this is a **git** tool, not a **GitHub** tool.
