### ISSUE TITLE
Github is still showing the old date

### ISSUE THREAD

**Issue by HironTez** [rixx/git-backdate#14]
> Locally:
![image](https://github.com/user-attachments/assets/1ccfef69-d8c3-4b38-a797-9d20dd7a4711)

> Github:
![image](https://github.com/user-attachments/assets/fa50c0db-cb23-4274-83ea-68a2aea523cc)

**Comment by rixx** [comment]
That's not a lot of details, so I'll be equally brief:

1. cannot reproduce
2. might be caching?
3. if you had given more details, I would try debugging things (ie do both commits show the same commit ID etc), but alas
4. if you want to debug this yourself, go to eg [this](https://github.com/HironTez/Chess/commit/a9dff0c13bf5fd927e4249e5a497924932ee4382.patch) url and check that both the date and the commit ID match your local data
5. ???
6. profit
7. for plausible deniability, consider anything you've pushed public, so pushing first one date and then the other to github should always imply that the first date is public and known
