### ISSUE TITLE
make this an actuall python package

### ISSUE THREAD

**Issue by Janik-Haag** [rixx/git-backdate#5]
Would be great if this would be an actual python package. So using setuptools, poetry, pdm or some other python packaging tool. I can also make a PR if doing so is okay?

**Comment by noqqe** [comment]
Would also be interested in this. Can contribute as well

**Comment by rixx** [comment]
Sure, if you want to make this happen, open a PR.

Out of curiosity: may I ask why? As this is a single executable, I feel like there's very few advantages in having a Python package, and quite some disadvantages: added maintenance, version bumping, PyPI releasing, switching to the next best hottest latest packaging format in two years, …. And especially as more and more systems switch to (rightfully!) disallowing global `pip install`s, regular users would increasingly only be able to use the Python package in a venv (or via a system package, which doesn't really need the Python packaging overhead …).

**Comment by rixx** [comment]
(Also please leave the repo structure as it is – I'm very fond of the fact that this is just a single executable and a documentation file. I'm willing to add one more file for the Python packaging nerds, but not an entire project structure.)

**Comment by Janik-Haag** [comment]
I would love to upstream this in nixpkgs and to do that in a proper way we should have an actual python package.

**Comment by rixx** [comment]
Huh, so you would also need me to upload the package to PyPI, and release versions?

(Gotta admit, I built this out into a repo because it was too fun to live in my script collection, but maybe I should have left it there and kept quiet. I maintain enough software as is, so it's very unlikely that you'll get any updates or releases or anything like that. Basically, you can add a single file to make it a package, and I can push it to PyPI, but I won't feel responsible for maintaining that file. If you miss out on updates, you can always open a new PR adjusting your packaging file.)

**Comment by athornton** [comment]
I mean I'm not saying I'm going to write a PR for you, and if I do it will definitely be outside of business hours, but it's fairly easy to, especially with the newish PyPi trusted publisher support, just, you know, push to PyPI whenever you cut a release from GitHub with the addition of a GitHub action.

So I if a PR were to happen, and you were to merge it, then what you'd have to do would be to set up the package name on PyPI, do the OIDC dance with GitHub once, and cut a Github release with a new version tag on each release, which is like three clicks and putting some text in a box.

**Comment by rixx** [comment]
This is silly. Closing as "not planned (to be implemented by me)". PRs welcome.

**Comment by rixx** [comment]
Felt a bit bad about closing this issue, so I reviewed the Python Packaging Guide. Turns out, providing a single executable file to be shared (assuming it requires no dependencies) is the [official recommendation](https://packaging.python.org/en/latest/overview/#python-modules)!

**Comment by athornton** [comment]
Fair, and yes, of course it's silly.  I enjoy ludicrously overengineering silly projects, which is why, if it ever happened, it'd be a PR from me.  Cool that it's the official recommendation.
